exports.seed = function (knex) {
  // Inserts seed entries
  return knex('rooms').insert([
    { house_id: 1, description: '1 single bed', available: true },
    { house_id: 1, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 1, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 2, description: '2 single beds', available: true },
    { house_id: 2, description: '6 bunk beds', available: true },
    { house_id: 3, description: '1 queen bed', available: true },
    { house_id: 4, description: '1 single bed', available: true },
    { house_id: 5, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 5, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 6, description: '1 single bed', available: true },
    { house_id: 7, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 7, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 7, description: '2 single beds', available: true },
    { house_id: 7, description: '6 bunk beds', available: true },
    { house_id: 8, description: '1 queen bed', available: true },
    { house_id: 8, description: '1 single bed', available: true },
    { house_id: 9, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 9, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 9, description: '1 single bed', available: true },
    { house_id: 9, description: '1 single bed', available: true },
    { house_id: 10, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 10, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 11, description: '2 single beds', available: true },
    { house_id: 11, description: '6 bunk beds', available: true },
    { house_id: 11, description: '1 queen bed', available: true },
    { house_id: 11, description: '1 single bed', available: true },
    { house_id: 12, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 12, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 13, description: '1 single bed', available: true },
    { house_id: 13, description: '1 single bed', available: true },
    { house_id: 13, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 14, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 14, description: '2 single beds', available: true },
    { house_id: 15, description: '6 bunk beds', available: true },
    { house_id: 16, description: '1 queen bed', available: true },
    { house_id: 16, description: '1 single bed', available: true },
    { house_id: 16, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 16, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 17, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 17, description: '1 single bed', available: true },
    { house_id: 17, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 17, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 18, description: '2 single beds', available: true },
    { house_id: 18, description: '6 bunk beds', available: true },
    { house_id: 19, description: '1 queen bed', available: true },
    { house_id: 19, description: '1 single bed', available: true },
    { house_id: 19, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 20, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 20, description: '6 bunk beds', available: true },
    { house_id: 21, description: '1 single bed', available: true },
    { house_id: 22, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 22, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 22, description: '2 single beds', available: true },
    { house_id: 22, description: '6 bunk beds', available: true },
    { house_id: 23, description: '1 queen bed', available: true },
    { house_id: 23, description: '1 single bed', available: true },
    { house_id: 24, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 24, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 24, description: '1 single bed', available: true },
    { house_id: 24, description: '1 single bed', available: true },
    { house_id: 25, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 25, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 26, description: '2 single beds', available: true },
    { house_id: 26, description: '6 bunk beds', available: true },
    { house_id: 26, description: '1 queen bed', available: true },
    { house_id: 27, description: '1 single bed', available: true },
    { house_id: 27, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 27, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 27, description: '1 single bed', available: true },
    { house_id: 28, description: '1 single bed', available: true },
    { house_id: 28, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 28, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 29, description: '2 single beds', available: true },
    { house_id: 29, description: '6 bunk beds', available: true },
    { house_id: 30, description: '1 queen bed', available: true },
    { house_id: 30, description: '1 single bed', available: true },
    { house_id: 30, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 30, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 31, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 31, description: '1 single bed', available: true },
    { house_id: 31, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 31, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 32, description: '2 single beds', available: true },
    { house_id: 32, description: '6 bunk beds', available: true },
    { house_id: 33, description: '1 queen bed', available: true },
    { house_id: 33, description: '1 single bed', available: true },
    { house_id: 33, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 34, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 34, description: '6 bunk beds', available: true },
    { house_id: 35, description: '1 single bed', available: true },
    { house_id: 35, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 35, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 35, description: '2 single beds', available: true },
    { house_id: 36, description: '6 bunk beds', available: true },
    { house_id: 36, description: '1 queen bed', available: true },
    { house_id: 37, description: '1 single bed', available: true },
    { house_id: 38, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 38, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 38, description: '1 single bed', available: true },
    { house_id: 39, description: '1 single bed', available: true },
    { house_id: 39, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 40, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 40, description: '2 single beds', available: true },
    { house_id: 41, description: '6 bunk beds', available: true },
    { house_id: 41, description: '1 queen bed', available: true },
    { house_id: 41, description: '1 single bed', available: true },
    { house_id: 42, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 43, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 44, description: '1 single bed', available: true },
    { house_id: 44, description: '1 single bed', available: true },
    { house_id: 44, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 44, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 45, description: '2 single beds', available: true },
    { house_id: 45, description: '6 bunk beds', available: true },
    { house_id: 46, description: '1 queen bed', available: true },
    { house_id: 46, description: '1 single bed', available: true },
    { house_id: 47, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 47, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 47, description: '1 single bed', available: true },
    { house_id: 47, description: '1 single bed', available: true },
    { house_id: 48, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 48, description: '1 queen bed, 2 single beds', available: true },
    { house_id: 48, description: '2 single beds', available: true },
    { house_id: 49, description: '6 bunk beds', available: true },
    { house_id: 49, description: '1 queen bed', available: true },
    { house_id: 50, description: '1 single bed', available: true },
    { house_id: 50, description: '2 double beds, 1 bunk bed', available: true },
    { house_id: 50, description: '1 queen bed, 2 single beds', available: true }
  ])
}
